name: CI/CD

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: |
          docker build -t myapp:latest .

      - name: Set up Minikube
        uses: medyagh/setup-minikube@v0.6.0
        with:
          kubernetes-version: 1.30.0
          driver: docker

      - name: Load image into Minikube
        run: |
          eval $(minikube docker-env)
          docker build -t myapp:latest .

      - name: Deploy to Minikube
        run: |
          kubectl apply -f deployment.yaml
          kubectl apply -f service.yaml

      - name: Wait for deployment rollout
        run: |
          kubectl rollout status deployment/myapp-deployment

      - name: Get Minikube service URL
        run: |
          minikube service myapp-service --url